### ISSUE TITLE
crossorigin error

### ISSUE THREAD

**Issue by newman330** [ErrorNull0/enZombiesPatches#1]
getting a crossorigin error for the spawing and gamestage patches for undead legacy

**Comment by ErrorNull0** [comment]
hi there. i can look into it. is it only UL mod and just enZombies you have installed? and can you get me the log of an example game session?

**Comment by newman330** [comment]
I only have UL installed
I think the error message says line 15

**Comment by ErrorNull0** [comment]
i tested with the latest Undead Legacy 2.5.47 and enZombies 2.6... and i can see yellow warnings errors when game starts up about biome attributions within spawning.xml, but i don't see any red errors or origin errors. then when i install the Undead Legacy patch, it fixes those yellow warnings. i'm not able to reproduce the errors you're mentioning. if you can get me a screenshot or a copy of your log file, then i can look further.

**Comment by newman330** [comment]
apologies, but i think my initial attempts at copying these files across didnt work correctly.  I have now got it working.  Sorry for the distraction.  Excellent mod - certainly spices things up a bit.

**Comment by ErrorNull0** [comment]
that's great to hear. glad you like them.
